사용자 회원가입을 spring security와 타임리프를 이용해 간단하게 구현
lbsProject/lbs_server pull request #14
Opened 2023-11-14 17:27 UTC by kanginkug

아직 변경해야 할것들과 추가 해야 할것들이 많다.

2023-11-18 13:20 UTC, s0nnyday requested changes
코드 보면서 궁금한 점들 답변 드렸습니다.
특히 User.java 에 import 하신 부분에 코멘트 확인 부탁드립니다.

2023-11-18 13:20 UTC, s0nnyday commented on src/main/java/lbs/lbs/entity/Authority.java
> +}
enum 으로 설정하신거 좋네요.

리뷰하며 공부용 작성]
* 장점
1. 리팩토링시 변경 범위가 최소화 됩니다.
- 내용의 추가가 필요하더라도, Enum 코드 외에 수정할 필요가 없습니다.

2023-11-18 13:20 UTC, s0nnyday commented on src/main/java/lbs/lbs/entity/JoinType.java
> +}
리뷰하면서 공부할 겸 enum 특징]
enum은 상수를 나타내는 데에만 사용되지 않고, 더 복잡한 로직이나 데이터를 갖는 객체로 확장될 수 있습니다. 이를 통해 코드의 가독성과 유지보수성을 향상시킬 수 있습니다.

entity 내에 Authority, JoinType 들어가는 이유가 있을까요?

public으로 하는 이유가?(진짜 몰라서)

2023-11-18 13:20 UTC, s0nnyday commented on src/main/java/lbs/lbs/entity/User.java
>  import jakarta.persistence.*;
import 할 때, jakarta.persistence.*로 전체 persistence 패키지 가져오기보다 필요한 것만 가져오는게 좋을 것 같은데 어떻게 생각하시나요?

리뷰하면서 공부]
* import jakarta.persistence.*;
  + jakarta.persistence 패키지는 Java Persistence API (JPA)의 일부입니다. JPA는 자바 어플리케이션에서 관계형 데이터베이스와 상호 작용할 수 있도록 도와주는 API입니다.

2023-11-18 13:20 UTC, s0nnyday commented on src/main/java/lbs/lbs/entity/User.java
> +    private JoinType joinType;
User 테이블에서 생년월일만 null 가능이고, 나머지는 다 not null 이었던 것 같은데 @Nullable 은 널값 가능 어노테이션인 것 같아서.. 틀렸다면 답변 부탁드립니다.

2023-11-18 13:20 UTC, s0nnyday commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
저는 아직 create 안 했는데... 하는 생각을 잠시 했는데 update로 해놔도 데이터베이스 없으면 테이블 생성을 해주네요. 변경하신거 좋은 것 같습니다.

코드 리뷰하면서 공부]
테이블 생성:
데이터베이스에 해당 엔터티에 매핑되는 테이블이 존재하지 않으면, 해당 테이블을 생성합니다.

테이블 업데이트:
데이터베이스에 이미 테이블이 존재하는 경우, Hibernate는 엔터티 클래스의 변경 내용을 기반으로 테이블을 업데이트합니다. 이는 새로운 열 추가, 제거, 데이터 타입 변경 등을 수행합니다.

2023-11-18 13:23 UTC, s0nnyday reviewed
UserRequestDto에 궁금한 부분이 있어서 확인, 답변 부탁드립니다.

2023-11-18 13:23 UTC, s0nnyday commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +    }
얘만 public 인 이유가 혹시 있을까요?

2023-11-18 14:04 UTC, s0nnyday reviewed
@AllArgsConstructor, @NoArgsConstructor 로 모든 필드 인자로 받는 생성자, 기본 생성자 안 만들어도 될까요?

2023-11-18 14:04 UTC, s0nnyday commented on src/main/java/lbs/lbs/controller/UserController.java
> +@RequiredArgsConstructor
코드리뷰하면서 공부]
@RequiredArgsConstructor
1. 이 어노테이션을 사용하면 생성자가 자동으로 생성됩니다.
2. 주로 final로 선언된 필드들을 파라미터로 받는 생성자를 자동으로 생성하여 코드의 가독성을 향상시킵니다.
3. @Autowired 없어도 의존성 주입이 가능하게 합니다.

위와 같다는데 어떤 목적으로 @RequiredArgsConstructor 쓰신건지 알 수 있을까요?

간단 추가 설명]
1. @NoArgsConstructor:
Lombok 어노테이션 중 하나로, 이 어노테이션을 사용하면 파라미터 없는 기본 생성자가 자동으로 생성됩니다.

2. @AllArgsConstructor:
Lombok 어노테이션 중 하나로, 이 어노테이션을 사용하면 모든 필드를 인자로 받는 생성자가 자동으로 생성됩니다.
주로 모든 필드를 초기화하는 생성자를 편리하게 만들 때 사용됩니다.

2023-11-18 14:18 UTC, s0nnyday commented on src/main/java/lbs/lbs/controller/UserController.java
> +        String bcPassword = bCryptPasswordEncoder.encode(userRequestDto.getPassword());
bCryptPasswordEncoder 이게 혹시 뭘까요?

2023-11-18 14:32 UTC, s0nnyday reviewed
어노테이션 사용에 관련하여 답변 주시면 감사하겠습니다.

2023-11-18 14:32 UTC, s0nnyday commented on src/main/java/lbs/lbs/controller/UserController.java
>      }
Q1. @ResponseBody 어노테이션을 한 줄 위에 말고 반환 타잎 앞에 쓰신거는 의도하신걸까요? 
한 줄 위에 쓰는걸로 저는 배웠는데 혹시 저렇게 쓰는게 어떤 장점이 있을까요? 

[코드리뷰 겸 공부]
@ResponseBody 어노테이션은 메서드 반환 타입 앞이나 메서드 선언 앞에 위치할 수 있습니다. 

[코드리뷰 겸 공부]
@RestController 가 아닌 @Controller 이기 때문에 @ResponseBody 어노테이션을 사용하여 해당 값이 HTTP 응답의 본문으로 처리되도록 명시해야합니다.

2023-11-18 14:38 UTC, s0nnyday reviewed
어노테이션과 테이블 구조 궁금증

2023-11-18 14:38 UTC, s0nnyday commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +@Setter
@AllArgumentConstructor, @NoArgumentConstructor 어노테이션 사용 안해도 될까요?

2023-11-18 14:38 UTC, s0nnyday commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +    }
1. 이게 무슨 테이블이죠??
2. 유저 관련해서는 컬럼이 10개로 알고있는데 (아이디,비밀번호,이름,생년월일,연락처,이메일,권한,비밀번호 틀린횟수,사용여부,가입 유형) 개수가 달라서 의문입니다.
3. 유저 닉네임은 저희 테이블 구조에 없던 것 같습니다!

2023-11-22 04:00 UTC, kanginkug commented on src/main/java/lbs/lbs/entity/JoinType.java
> +}
Authority는 관리자만 들어갈 수 있는 페이지를 따로 만들 때 사용하기 위해 넣었고 
JoinType은 KAKAO, NAVER, GOOGLE, LBS의 비중을 확인할 수 있고 각각의 로그인에 따라 유저 정보가 잘 저장되었는지 확인 하기 위해 넣었습니다.
public은 p 자동완성 하다가 public으로 된듯 합니다.

2023-11-22 04:07 UTC, kanginkug commented on src/main/java/lbs/lbs/entity/User.java
>  import jakarta.persistence.*;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.GenerationType;
를 자동완성으로 다 넣으면 자동으로 import jakarta.persistence.*;로 변환되어 사용했는데 챗gpt 검색 결과 성능적인 면에선 큰 차이가 없기 때문에 import jakarta.persistence.*;가 가독성면에서 좋다고 합니다. 
 어떤 면에서 더 좋을지 알려주시면 감사하겠습니다.

2023-11-22 04:11 UTC, kanginkug commented on src/main/java/lbs/lbs/entity/User.java
> +    private JoinType joinType;
이 부분은 생년월일만 null가능인게 맞습니다 수정하도록 하겠습니다. 
@nullable은 이후 false로 수정하였습니다.

2023-11-22 04:17 UTC, kanginkug commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
제가 알기로 create는 프로젝트를 실행할 때 기존에 있던 테이블도 삭제하고 다시 만들기 때문에 내용물도 다 지워지는 것으로 알고 있습니다. 
각자 테스트할 때 편한 방식으로 바꿔가며 설정하면 될 것 같습니다.

2023-11-22 04:19 UTC, kanginkug commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +    }
기존에 참고하던 프로젝트에서 public으로 되어있어서 public으로 했지 이유는 생각해보지 않았습니다. 
따로 공부해보도록 하겠습니다.

2023-11-22 04:22 UTC, kanginkug commented on src/main/java/lbs/lbs/controller/UserController.java
> +@RequiredArgsConstructor
보통은 생성자를 만들어서 @autowired를 사용해야 spring에 맞게 사용하는 것이지만 써주신 것처럼 @requiredargsconstructor을 사용하면 간단하게 사용할 수 있기 때문에 사용했습니다.

2023-11-22 04:24 UTC, kanginkug commented on src/main/java/lbs/lbs/controller/UserController.java
> +        String bcPassword = bCryptPasswordEncoder.encode(userRequestDto.getPassword());
스프링 시큐리티 프레임워크에서 제공하는 클래스 중 하나로 비밀번호를 암호화하는 데 사용할 수 있는 메서드를 가진 클래스입니다.
회원가입을 할 때 입력받은 패스워드를 UserRequestDto로 받아오고 bCryptPasswordEncoder를 사용하면 간단하게 암호화를 할 수 있습니다.

2023-11-22 04:28 UTC, kanginkug commented on src/main/java/lbs/lbs/controller/UserController.java
>      }
해당 api는 유저가 회원가입을 완료했을 때 웹페이지에 join이라는 글이 나오게끔 하는 테스트 api 입니다. 
앞으로 수정해서 회원가입을 완료하면 회원가입 페이지로 가기 전 페이지로 이동하게 하는 코드로 수정할 예정입니다.

2023-11-22 04:36 UTC, kanginkug commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +@Setter
@Setter 어노테이션을 사용하지 않는 것이 좋으므로 @AllArgumentConstructor, @NoArgumentConstructor을 사용해야 할 것 같습니다.

2023-11-22 04:42 UTC, kanginkug commented on src/main/java/lbs/lbs/dto/UserRequestDto.java
> +    }
1. 유저 엔티티를 그대로 받아오는 것은 좋지 않기 때문에 dto라는 받을 데이터만 담는 상자에 담아서 받아오는 것이 좋다고 배워서 dto를 생성했습니다.
2. userRequestDto에는 유저가 입력하고 전송한 값들만 들어가기 때문에 갯수가 다르게 됩니다.
3. 생각해보니 게시글이나 댓글을 볼 때 카카오, 구글, 네이버, LBS 아이디가 보이기 보다는 닉네임을 설정해서 보여주는 것이 좋다고 생각해서 수정했습니다. 회의하지 않고 설명도 쓰지 않고 수정한 점 죄송합니다.

2023-11-22 05:06 UTC, kanginkug commented on src/main/java/lbs/lbs/entity/User.java
> +    private JoinType joinType;
생각해보니 auth, pwErrChk, userYN, joinType는 기본적으로 null값이 들어가지 않게 default 값이 들어가도록 했기 때문에 email과 phone만 not null 이 되도록 하면 될 것 같은데 어떻게 생각하시나요?

2023-11-22 05:15 UTC, merged